// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorWebAssem.TaskOrganizer.Deliverable
{
    public partial class Deliverable
    {
        public string CourseCode { get; set; }
        public string Task { get; set; }
        public DateTime DueDate { get; set; }
        public string AdditionalNotes { get; set; }
        public bool IsDone { get; set; }

        public Deliverable ()
        {
            CourseCode = "----";
            Task = "----";
            DueDate = DateTime.Now;
            AdditionalNotes = "----";
            IsDone = false; 
        }
        public Deliverable(string courseCode, string task, DateTime dueDate, string note)
        {
            CourseCode = courseCode;
            Task = task;
            DueDate = dueDate.Date;
            AdditionalNotes = note;
        }
    }
}